Repository falcosecurity/syscalls-bumper, pull requests merged in 2023-10, with the labels that each got.

#16 chore: bump schema version too when needed.
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, dco-signoff: yes, size/M

#17 docs: add license header and spdx id
  main.go
Labels: lgtm, approved, dco-signoff: yes, size/S

#13 new: add support to bump ia32->64 syscalls map too.
  main.go
Labels: lgtm, approved, dco-signoff: yes, size/M

#18 new: print architectures for each syscall in report.
  main.go
Labels: lgtm, approved, dco-signoff: yes, size/S

#19 chore: properly add more ia32 syscalls force-translations.
  main.go
Labels: lgtm, approved, dco-signoff: yes, size/L
