Repository falcosecurity/syscalls-bumper, pull requests merged in 2023-11, with the labels that each got.

#20 fix: fixed syscalls-table github repo paths.
  main.go
Labels: lgtm, approved, dco-signoff: yes, size/XS

#22 Add ppc64le as a supported architecture
  README.md
  main.go
Labels: lgtm, approved, dco-signoff: yes, size/XS

#24 chore: properly sort ia32 map.
  main.go
Labels: lgtm, approved, dco-signoff: yes, size/S

#23 chore(ci): release artifacts and docker images for all supported architectures
  .github/workflows/release.yml
  .goreleaser.yml
Labels: lgtm, approved, dco-signoff: yes, size/M

#25 fix: sort architectures in report.md
  main.go
Labels: lgtm, approved, dco-signoff: yes, size/XS

#26 chore: disable pie.
  .github/workflows/release.yml
  .goreleaser.yml
  Makefile
Labels: lgtm, approved, dco-signoff: yes, size/XS
